name: build

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Start Postgres
        uses: harmon758/postgresql-action@v1
        with:
          postgresql version: "14"
          postgresql user: ci_user
          postgresql password: ci_password

      - name: Setup database
        env:
          RAILS_ENV: test
        run: |
          cp config/database.ci.yml config/database.yml
          bundle exec rails db:create db:schema:load

      - name: Run tests
        run: bundle exec rspec
